apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-resources
spec:
  background: false
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: add-requests-limits
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      any:
      - key: "{{request.operation}}"
        operator: In
        value: [CREATE, UPDATE]
    mutate:
      foreach:
      - list: "spec.containers"
        patchStrategicMerge:
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
              