# Kubeval configuration for Kubernetes manifest validation
# This file configures kubeval behavior for the namespace auto-shutdown system

# Kubernetes version to validate against
kubernetes-version: "1.29.0"

# Schema location - use official Kubernetes schemas
schema-location: "https://raw.githubusercontent.com/instrumenta/kubernetes-json-schema/master"

# Additional schema locations for CRDs
additional-schema-locations:
  - "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/crds"
  - "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd"

# Files and directories to ignore
ignore-missing-schemas: true

# Strict validation mode
strict: false

# Exit on first error
exit-on-error: false

# Output format (tap, json, junit)
output: tap

# Quiet mode
quiet: false

# Skip validation for these kinds
skip-kinds:
  - "Kustomization"
  - "Application"  # ArgoCD Application CRD
  - "AppProject"   # ArgoCD AppProject CRD

# Skip validation for these files
ignore-filename-patterns:
  - "kustomization.yaml"
  - "kustomization.yml"
  - ".yamllint.yml"
  - "docker-compose*.yml"
  - "docker-compose*.yaml"