extends: relaxed

rules:
  # Line length - more flexible for Kubernetes manifests
  line-length:
    max: 120
    level: warning

  # Indentation - strict for consistency
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Truthy values - allow common Kubernetes values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Comments formatting
  comments:
    min-spaces-from-content: 1

  # Document formatting
  document-start:
    present: false  # Kubernetes manifests often don't use ---

  document-end:
    present: false

  # Empty lines control
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Key duplicates
  key-duplicates: enable

  # Trailing spaces
  trailing-spaces: enable

# Ignore patterns for files that shouldn't be linted
ignore: |
  .git/
  node_modules/
  build/
  dist/
  coverage/
  .vscode/
  .idea/
  *.log
  *.tmp
  .env*
