---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler-sa
  namespace: encendido-eks
  annotations:
    # IMPORTANTE: Reemplaza 226633502530 con tu AWS Account ID real
    eks.amazonaws.com/role-arn: arn:aws:iam::226633502530:role/NamespaceControllerRole
  labels:
    app: namespace-scaler
    component: serviceaccount
---
# ClusterRole con permisos mínimos necesarios
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-scaler-role
  labels:
    app: namespace-scaler
    component: rbac
rules:
  # Permisos para leer namespaces
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  
  # Permisos para gestionar deployments
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]
  
  # Permisos para crear eventos
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  
  # Permisos para leer pods (para health checks)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
# ClusterRoleBinding para vincular el ServiceAccount con el ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-scaler-binding
  labels:
    app: namespace-scaler
    component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-scaler-role
subjects:
  - kind: ServiceAccount
    name: scaler-sa
    namespace: encendido-eks